### ISSUE TITLE
Support footnotes after paragraph and inline definitions

### ISSUE THREAD

**Issue by johnlane** [gettalong/kramdown#497] opened 2018-03-01 11:42 UTC
I don't know if this is possible but I haven't been able to find it.

Sometimes, in a long document, it would be better if some *footnotes* could appear after the paragraph they're referenced by. These annotations might go by a different name perhaps.

Also, specifying notes of either variety inline would be handy. Perhaps footnotes get auto numbered (1,2,3) and paragraph notes get a bullet or auto-lettered (a,b,c). Most notes are referenced only once and the assigned number is irrelevant. Specific references might be used where needed. 

Something like this...
````
This is a page[^](goes at end of doc) with a footnote. This paragraph has a note[^^](note after it) below it. 

This footnote[^ref1] has a specific ref as does this paragraph note[^^ref2].

Specific refs allow footontes[^ref1] and paragraph notes [^^ref2] to be reused.

[^ref1]: a referencable footnote.
[^^ref2]: a referencable paragraph note.

**Comment by gettalong** [comment] 2018-03-01 17:58
There is no notion of "paragraph footnotes" in kramdown. And as far as typography goes I know that there are *footnotes* (appearing at the bottom of the printed page) and *endnotes* (appearing at the end of a section) but I haven't heard of paragraph notes.

**Comment by johnlane** [comment] 2018-03-01 22:36
Yes that's the printed analogy - end of page and end of section.

But with a web page, which might be very long, you end up with page == section. Sometimes I would like to place a note outside the text flow but close to it so the reader can see it quickly see it without clicking a link or scrolling to the end of the page.

With a printed page a quick glance to the bottom of a page is easy, paging forward to the end of a section is hard. The analogy I was after with a content on a web page was to make a quick glance close to where I am (i.e. end of paragraph) possible because having to scroll or click a link is hard (especially if the device isn't a desktop computer).

**Comment by ccorn** [comment] 2018-03-06 23:49
Some thoughts:

* LaTeX knows a `{minipage}` environment. Perhaps the OP wishes for a kramdown analogue.
* In HTML, page = section, yes, so footnotes look much like endnotes there. Now the thing with endnotes (as opposed to footnotes) is that you know precisely where in the document they will show up. So there is not much benefit in using endnotes instead of hyperlinks like `[<sup>3</sup>](#note3)`. If you use such hyperlinks instead, you are in direct control of the placement of the target, as you wish.
* In that sense, the issue is that the HTML generator generates footnotes that are placed like endnotes by default. But some CSS wizardry might dynamically place the footnote `<div>` more footnote-like at the bottom of the browser window (as opposed to the bottom of the web page). In general, the accompanying loss of window height for the main text could be unnerving, but you might want to try that approach.

**Comment by ousia** [comment] 2018-05-02 16:44
@gettalong,

would it be possible that _Kramdown_ could have inline footnotes?

This is the way that _Markdown_ for `pandoc` implements them:

```
Main text.^[Inline footnote.] 
```

Congratulations and many thanks for your excellent work with _Kramdown_.

**Comment by gettalong** [comment] 2018-05-03 18:45
@ousia Probably not for the 1.x series to avoid compatibility problems but for a future 2.0 it's possible.

**Comment by ousia** [comment] 2018-05-03 19:18
@gettalong, many thanks for your reply.

Sorry, I’m not sure I explained myself right. I’m not proposing to change any existing feature, but to have an alternative and brand new method for notes.

BTW, is there an ETA for version 2?

Many thanks again for your help.

**Comment by gettalong** [comment] 2018-05-03 19:52
@ousia I got that but introducing a new feature *would* probably change existing documents that already use that syntax in a different way.

And sorry, no ETA for version 2.0 at this moment.

**Comment by gettalong** [comment] 2018-06-24 07:08
@johnlane @ousia I have moved this issue to "Feature Requests" project that lists the issues that need a pull request or will be done for the 2.0 release. Therefore I close this issue now but feel free to still comment on it.

**Closed by gettalong** 2018-06-24 07:08 UTC
Labels: enhancement
