### ISSUE TITLE
GFM mode does not support check boxes

### ISSUE THREAD

**Issue by binduwavell** [gettalong/kramdown#346] opened 2016-06-12 04:18 UTC
-[ ] is unchecked
-[x] is checked
---
- [ ] is unchecked
- [x] is checked

**Comment by gettalong** [comment] 2016-06-12 16:19
Pull requests are welcome if this feature should be implemented.

**Comment by imkean** [comment] 2016-06-28 11:50
+ 1

**Comment by BobWalsh** [comment] 2016-07-31 00:46
+1

**Comment by winniehell** [comment] 2016-08-08 19:41
Dear people from the future, if you want to `+1`, please use this feature from the future: https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments :smile:

**Comment by gettalong** [comment] 2016-08-14 09:48
Can anyone provide the HTML output for this?

And use cases for this feature? I imagine this being nice in an issue or pull request but what should it do when used with kramdown on a plain website?

**Comment by winniehell** [comment] 2016-08-15 19:21
@gettalong 

```markdown
- [ ] first item
- [x] second item
```

would result in:

```html
<ul class="contains-task-list">
<li class="task-list-item enabled"><input type="checkbox" class="task-list-item-checkbox"> first item</li>
<li class="task-list-item enabled"><input type="checkbox" class="task-list-item-checkbox" checked=""> second item</li>
</ul>
```

for logged in user with permissions and

```html
<ul class="contains-task-list">
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" disabled=""> first item</li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" checked="" disabled=""> second item</li>
</ul>
```

for logged out user or user without permission on GitHub.

Since kramdown does not know about any permissions I suggest dropping the `enabled` / `disabled`. So this would be a great output:

```html
<ul class="task-list">
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox"> first item</li>
<li class="task-list-item"><input type="checkbox" class="task-list-item-checkbox" checked=""> second item</li>
</ul>
```

> And use cases for this feature? I imagine this being nice in an issue or pull request but what should it do when used with kramdown on a plain website?

Please keep in mind that kramdown is not only used for plain websites. :smile: GitLab is actually considering using kramdown for all its Markdown rendering: https://gitlab.com/gitlab-org/gitlab-ce/issues/18552

**Comment by winniehell** [comment] 2016-08-15 19:33
one corner case:

```markdown
- [x] foo
- [ ] bar

[ ]: http://space.example
[x]: http://x.example
```

renders like this on GitHub:

- [x] foo
- [ ] bar

[ ]: http://space.example
[x]: http://x.example

**Comment by winniehell** [comment] 2016-08-15 19:41
Another request for Markdown rendering on GitLab was to support arbitrary whitespace within `[ ]`. See also https://gitlab.com/gitlab-org/gitlab-ce/issues/2949

**Comment by gettalong** [comment] 2016-08-15 21:36
@winniehell Thanks for your feedback!

Regarding the output: I would prefer the HTML output with the checkboxes disabled because this would work on any website, not just "checkbox aware" sites. This would have the advantage that clicking on the checkboxes wouldn't change the state of them and would lead to users expecting some change.

As for the corner case: This is no corner case in my opinion since the syntax description would say something like "If the list item marker is followed by an opening square bracket, a space or an uppercase/ lowercase ASCII 'x' character, and a closing square bracket, ...". So if the user doesn't use this, it won't work.

If we would handle your supposed corner case, what would you do about intermingled zero-width spaces? En or em spaces? I don't think such things can easily be handled in a general way, especially if you want to handle *all* possibly Unicode characters that look similar...

**Comment by gettalong** [comment] 2016-08-15 21:39
@winniehell The corner case I mentioned was for the arbitrary whitespace case.

As for the link case: I think that handling them as checkboxes would be the right call here, and not treating them as reference links.

**Comment by winniehell** [comment] 2016-08-15 22:45
@gettalong 

> I would prefer the HTML output with the checkboxes disable

Sure, that makes sense. :+1: 

> This is no corner case in my opinion

Maybe corner case wasn't the right term. :wink: It's just a situation where it has to be decided whether task lists or links have precedence.

> I think that handling them as checkboxes would be the right call here

I actually prefer that myself, too. :smile: I think that case is more likely.

> what would you do about intermingled zero-width spaces? 

I would have used `[:blank:]` to match the space: http://rubular.com/r/ADZYvFCrsM

**Comment by gettalong** [comment] 2016-08-16 08:31
Using a Unicode character property matcher like `[:blank:]` would potentially lead to very confusing results, see http://rubular.com/r/aqgr63mPSS where I amended your example with some more possible variations.

I would stay in the ASCII world and just the simple space and nothing else. In the issue you link the problem is not that the user doesn't want to use spaces but that he accidentally uses non-breaking spaces due to OS X keyboard layout. We can't really solve that problem...

**Comment by winniehell** [comment] 2016-08-16 09:32
> would potentially lead to very confusing results

I am not sure that I agree the result is confusing but let's not discuss about spaces here. :smile: 

> due to OS X keyboard layout. We can't really solve that problem...

That sounds desperate but I get your point. :wink:

**Comment by gettalong** [comment] 2016-08-16 10:46
Not really desperate since I'm not using OS X anymore :wink:

**Comment by gettalong** [comment] 2016-11-05 06:55
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Closed by gettalong** 2016-11-05 06:55 UTC
Labels: needs pull request
