### ISSUE TITLE
Periods should be allowed in HEADER_ID and ALD_TYPE_ID_NAME

### ISSUE THREAD

**Issue by cabo** [gettalong/kramdown#303] opened 2016-01-30 16:40 UTC
There is a longstanding tradition to allow periods in names that are turned into XML IDs, just as are colons and hyphens.
This is probably hard to do in ALD_TYPE_ID_NAME (conflict with class name syntax).  (Should there be a way to escape a period or maybe any other character going into an ID name?  Maybe not, as this always can be phrased as "id=...".)
Conversely, it seems trivial to allow periods in HEADER_ID.

**Comment by gettalong** [comment] 2016-02-18 16:07
As you have pointed out, in ALD_TYPE_ID_NAME it is not easily possible but in HEADER_ID it is.

However, I will defer this to the next major version.

**Comment by aoles** [comment] 2016-09-26 12:18
Dear Thomas,

the lack of periods in header IDs causes the following incompatibility issue of pandoc-generated markdown files which serve as input to the nanoc site generator, which in turn uses kramdown to convert them to html. 

[Kramdown documentation](http://kramdown.gettalong.org/converter/html.html#auto-ids) says: *The rules on how header text is converted to an identifier are based on the rules specified by Pandoc.* However, kramdown's rules differ in the way periods are handled: while they are retained by pandoc, kramdown removes them.

The problem appears when I use pandoc to generate a TOC. When I convert a file containing
```
# A. Header
```
with the command `pandoc header.md --to markdown_strict --from markdown --standalone --table-of-contents` I get

```
-   [A. Header](#a.-header)

A. Header
=========
```

But once the file is rendered to html by kramdown, the auto-generated hyperlink is incorrect as the kramdown header id is `a-header`, and not `a.-header`.

Do you think this could be addressed soon?

Thanks,
Andrzej

**Comment by gettalong** [comment] 2016-09-27 05:01
@aoles As written this can only be addressed in the next major release since it would invalidate quite many currently working documents.

The problem is that you are trying to use two different Markdown libraries which will not work in most cases anyway.

kramdown does provide a table of contents feature for the HTML converter, see <http://kramdown.gettalong.org/converter/html.html#toc>. So there is no need to use another tool for this.

**Comment by aoles** [comment] 2016-09-27 08:57
Thank you @gettalong for your quick response and for pointing out to me the kramdown TOC feature! This is very helpful, I will most probably switch to it in my workflow.

Just some background information why I need to use both pandoc and kramdown: My specific use case involves the creation of pages for a website compiled with nanoc. These are generated  from .Rmd documents, which contain R code chunks evaluated during compilation; the output is then further processed with pandoc. The final html version is generated by kramdown from the resulting .md document. That's why it's important to me that pandoc mardown is compatible with kramdown.

Thanks for all your work on kramdown - I'm looking forward to the upcoming release. 

Cheers,
Andrzej

**Comment by gettalong** [comment] 2016-09-27 14:28
@aoles Note that the upcoming releases *won't* have this change in them since this change will only be incorporated into the 2.x release.

I still don't fully understand why you need two Markdown processors. If you already use Pandoc, than just use the HTML that Pandoc generates. Otherwise use only kramdown. Using two different Markdown converters and expecting complete feature parity is not going to work for most Markdown converter pairings.

**Comment by aoles** [comment] 2016-09-27 14:50
@gettalong thanks for clarifying!

I use this 2-step approach because I need intermediate output containing document body which gets rendered within the website template by nanoc. Sure, it would be also possible to generate HTML output in first place - for this I would probably just need to use a custom stripped-down pandoc template. I will certainly consider this as an alternative if things don't work out with the current approach. Anyway, thanks for your help!

Cheers,
Andrzej

**Comment by gettalong** [comment] 2016-11-05 06:56
Closed because feature request issues are now tracked through a dedicated project - see https://github.com/gettalong/kramdown/projects/1

**Closed by gettalong** 2016-11-05 06:56 UTC
Labels: enhancement
