### ISSUE TITLE
Japanese chars combined with MD syntax are not converted

### ISSUE THREAD

**Issue by JonasPospichal** [gettalong/kramdown#799] opened 2024-02-07 08:54 UTC
Hi,

Our documentation platform provider Zoomin Software utilizes kramdown for conversions of MD to HTML, we came across an interesting problem that the provider is unable to solve on their end. When converting Japanese text with MD syntax and some form of brackets - ([{ - the MD tags do not get converted. See the example below, look for the ** tags:

```
**[Conﬁguration Center]**をクリックし、ユーザログイン名に**admin**、パスワードに**admin**と入力します。**[システム]**>**[インターフェース設定]**>**[管理インターフェース1]**で、IPアドレスの設定を行います(GUIを使用したIP設定の管理の図を参照)。
IPアドレスを設定し、**[保存]**をクリックします。IPアドレスが変更され、デバイスが使用不可になります。10秒ほど待ち、デバイスをコンピュータから取り外し、管理インターフェースをLANネットワークに接続します。DHCPによる設定を行うIPアドレスの設定が完了したら、電源ボタンを短く押し、デバイスがオフになるまで待ちます。デバイスがオフになったら、もう一度オンにします。数分後、DHCPプロトコルからIPアドレスが取得されます。固定IPアドレスの設定が完了している場合は、デバイスをオフにする必要はありません。
```
This produces the following HTML code (also look for the ** tags):

```
<p><strong>[Conﬁguration Center]<strong>をクリックし、ユーザログイン名に</strong>admin</strong>、パスワードに<strong>admin</strong>と入力します。<strong>[システム]</strong>&gt;<strong>[インターフェース設定]</strong>&gt;**[管理インターフェース1]**で、IPアドレスの設定を行います(GUIを使用したIP設定の管理の図を参照)。</p>
<p>IPアドレスを設定し、**[保存]**をクリックします。IPアドレスが変更され、デバイスが使用不可になります。10秒ほど待ち、デバイスをコンピュータから取り外し、管理インターフェースをLANネットワークに接続します。DHCPによる設定を行うIPアドレスの設定が完了したら、電源ボタンを短く押し、デバイスがオフになるまで待ちます。デバイスがオフになったら、もう一度オンにします。数分後、DHCPプロトコルからIPアドレスが取得されます。固定IPアドレスの設定が完了している場合は、デバイスをオフにする必要はありません。</p>
```

Is there any way how to fix this or influence this behavior?

Thank you!

Regards,

Jonáš.

**Comment by gettalong** [comment] 2024-02-07 09:24
Could you reduce the problem to a minimal case because I'm not sure what exactly you mean?

Is the following the behaviour that you think is invalid:

~~~
**[Conﬁguration Center]**をクリックし、ユーザログイン名に**admin**
~~~

~~~ html
<p><strong>[Conﬁguration Center]</strong>をクリックし、ユーザログイン名に<strong>admin</strong></p>
~~~

**Comment by JonasPospichal** [comment] 2024-02-07 09:40
Hi Thomas,

Thanks for a swift reply.
No, not really. This is the smallest possible example of that behavior:
MD:
```
IPアドレスを設定し、**[保存]**をクリックします。
```
HTML:
```
<p>IPアドレスを設定し、**[保存]**をクリックします。(...)</p>
```
The ** ** pairs are not converted into the <strong></strong> pairs.

**Comment by gettalong** [comment] 2024-02-07 10:32
When I run your example through the kramdown binary, it gives me this output:

~~~ html
<p>IPアドレスを設定し、<strong>[保存]</strong>をクリックします。</p>
~~~

which looks correct.

Maybe there is something else at play?

**Comment by JonasPospichal** [comment] 2024-02-07 10:35
Thanks, Thomas. It definitely looks like it. I'll check with our provider. Apologies for taking your time.

**Comment by gettalong** [comment] 2024-02-07 11:48
No problem! :smile: I will close the issue. If it turns out it can be reproduced with kramdown alone, please let me know.

**Closed by gettalong** 2024-02-07 11:48 UTC
