### ISSUE TITLE
Incorrect interpretation with line break in SHELL

### ISSUE THREAD

**Issue by Merikanto** [gettalong/kramdown#628] opened 2019-10-11 01:46 UTC
This is my config:

```
markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    default_lang: shell
    hard_wrap: true
    css_class: 'syntax'
```

And after I set the default language to SHELL, there're problems with line breaks: **It doesn't interpret RETURN / ENTER as link break**. 

For instance, normally a shell script should look like this:

```
for n in {0..4}; do
	if [[ $n == 2 ]]; then
		continue	
	fi
	echo $n
done
```

However, it looks like this in kramdown's renderer:

```
for n in {0..4}; do if [[ $n == 2 ]]; then continue  fi  echo 
$n done
```

I checked my other settings, and once I changed the default lang to almost ANY OTHER language, this problem disappears. Bu every time with SHELL, codes got all messed up.

Thanks!

**Comment by gettalong** [comment] 2019-10-11 09:28
Can you please provide a simple sample input file and the output you get when running just kramdown and nothing else (e.g. no Jekyll)?

**Comment by Merikanto** [comment] 2019-10-13 20:04
Hey do think it's Jekyll's renderer's problem? But why it's only about SHELL?

**Comment by gettalong** [comment] 2019-10-13 21:03
If you can reproduce the problem with just kramdown, I can investigate. Otherwise the possibilities are too much for me to have a look at...

**Comment by ashmaroli** [comment] 2019-10-14 05:38
Since this issue is regarding code-blocks and syntax-highlighting, you may want to additionally check if this issue can be reproduced with vanilla Rouge (i.e. without involving kramdown or Jekyll in the test environment)

**Comment by gettalong** [comment] 2020-04-16 21:30
@Merikanto When I use your example code like this:

~~~~~
~~~shell
for n in {0..4}; do
        if [[ $n == 2 ]]; then
                continue
        fi
        echo $n
done
~~~
~~~~~

I get the following output:

~~~html
<pre><code class="language-shell">for n in {0..4}; do
        if [[ $n == 2 ]]; then
                continue
        fi
        echo $n
done
</code></pre>
~~~

This seems to be right because line breaks in `<pre>` tags are respected.

I will close the issue for now since you didn't provide sample input that fails for you. Feel free to comment with the needed information to reproduce the problem and I will re-open the issue.

**Closed by gettalong** 2020-04-16 21:30 UTC
