### ISSUE TITLE
kramdown binary bug

### ISSUE THREAD

**Issue by pavelvasev** [gettalong/kramdown#250] opened 2015-05-04 14:34 UTC
Windows 7, Ruby 1.8.7:
Running kramdown from command line produce:
```
C:/Ruby187/lib/ruby/gems/1.8/gems/kramdown-1.7.0/bin/kramdown:40:in `<=>': undefined method `<=>' for :remove_block_html_tags:Symbol (NoMethodError)
        from C:/Ruby187/lib/ruby/gems/1.8/gems/kramdown-1.7.0/bin/kramdown:40:in `sort'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/kramdown-1.7.0/bin/kramdown:40
        from C:/Ruby187/lib/ruby/1.8/optparse.rb:791:in `initialize'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/kramdown-1.7.0/bin/kramdown:16:in `new'
        from C:/Ruby187/lib/ruby/gems/1.8/gems/kramdown-1.7.0/bin/kramdown:16
        from C:/Ruby187/bin/kramdown:23:in `load'
        from C:/Ruby187/bin/kramdown:23
```
https://github.com/gettalong/kramdown/blob/master/bin/kramdown#L40

**Comment by gettalong** [comment] 2015-05-04 15:28
Thanks for reporting this but fixing a bug for the outdated 1.8.7 version is not high a high priority on my TODO list.

Ruby 1.8.7 is still supported, though, so this will be fixed with the next release.

**Comment by gettalong** [comment] 2015-07-01 06:18
I tried to reproduce the problem on Ruby 1.8.7p249 but this just works since `Symbol#<=>` is defined.

**Closed by gettalong** 2015-07-01 06:18 UTC
Labels: bug, needs pull request
