### ISSUE TITLE
Unexpected handling of line break in link reference

### ISSUE THREAD

**Issue by dgw** [gettalong/kramdown#639] opened 2020-01-30 12:14 UTC
Kramdown breaks the link when hard-wrapped text contains a line break inside the brackets (`[]`) of a link reference. Here's a minimal example, which I saved as `test.md` in my freshly cloned kramdown repo root:

```md
Long line with [a reference link][
name-of-ref] embedded at the end.

[name-of-ref]: https://github.com/gettalong/kramdown
```

Running `bin/kramdown < test.md` on this gives:

```
<p>Long line with [a reference link][
name-of-ref] embedded at the end.</p>

Warning: No link definition for link ID ' name-of-ref' found on line 1
```

I'm no expert on the Markdown syntax, so maybe this form is technically invalid according to some official specification. But I'd like to point out that in non-exhaustive tests I've not managed to find another Markdown renderer that fails on this case.

Vim (my install, at least) highlights the syntax like any other valid link. [Dillinger.io](https://dillinger.io/) and [StackEdit.io/app](https://stackedit.io/app) (online Markdown editors) both render the link as expected, as does GitHub:

> Long line with [a reference link][
name-of-ref] embedded at the end.

[name-of-ref]: https://github.com/gettalong/kramdown

**Comment by gettalong** [comment] 2020-01-30 14:36
This works as intended, see https://kramdown.gettalong.org/syntax.html#reference-links.

The line break is converted to a space character, so `[ name-of-ref]: https://github.com/gettalong/kramdown` for the link definition will work.

If you don't want to change link identifier itself, I recommend putting a space between the closing and opening brackets so that the opening bracket is not separated from the following text.

**Closed by gettalong** 2020-01-30 14:36 UTC

**Comment by dgw** [comment] 2020-01-30 17:05
So just like that, no concern for the behavioral inconsistency between Kramdown and other Markdown renderers? I'd expect this to be a concern at least for the GFM mode, which is intended to emulate GitHub (where the example case works).

**Comment by gettalong** [comment] 2020-01-30 21:22
Since there is no standard to adhere to and there are certainly many other differences between each and every Markdown implementation, no, I don't think that this is a problem.

As always: If you write Markdown, you don't really write Markdown (except if you are using the Markdown.pl implementation) but you write kramdown, CommonMark, PHP Markdown Extra, ... If you use a different implementation on your text, you *may* get a similar or sometimes even equivalent result, but there is no guarantee. So best choose your Markdown implementation and then follow its syntax.

As for the kramdown GFM parser: It is based on the kramdown parser but already with many changes. So if you think that this is a bug in the GFM parser, please file an issue at https://github.com/kramdown/parser-gfm/issues
